language: ruby
bundler_args: --without development
rvm:
  - 1.9.3

before_install:
  - gem update --system
  - rvm @default,@global do gem uninstall -ax bundler
  - gem install bundler --pre

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "rake db:migrate"
  - "rake sunspot:solr:start"
