common:
  facebook_scopes: "offline_access,read_stream,email"
  heroku_app_url: "http://voto-como-vamos.herokuapp.com"
  facebook_permission_request_url: "http://www.facebook.com/connect/uiserver.php"

development:
  facebook_app_id: 342716239136799
  facebook_secret: fc98aac77fe38f52742a44ec414cc1ba
  facebook_app_url: "http://apps.facebook.com/342716239136779"

test:
  facebook_app_id: 341926772543413
  facebook_secret: 14a850bdc51644e279dca141408208ba
  facebook_app_url: "http://apps.facebook.com/341926772543413"

staging:
  facebook_app_id: 250842391695084
  facebook_app_url: "http://apps.facebook.com/250842391695084/"

production:
  facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
  facebook_app_url: "http://apps.facebook.com/<%= ENV['FACEBOOK_APP_ID'] %>"
