common:
  facebook_scopes: "offline_access,read_stream,email"
  heroku_app_url: "http://voto-como-vamos.herokuapp.com"
  facebook_permission_request_url: "http://www.facebook.com/connect/uiserver.php"
  email_sender: "sistema@votocomovamos.com.br"
  exception_sender: "noreply@votocomovamos.com.br"
  exception_recipient: "votocomovamos@thoughtworks.com"
  fqdn: "www.votocomovamos.com.br"
  mailtrap_io_user: "votocomovamos"
  mailtrap_io_password: "7abaf1e52c5bc55d"

development:
  facebook_app_id: 342716239136799
  facebook_secret: fc98aac77fe38f52742a44ec414cc1ba
  facebook_app_url: "http://apps.facebook.com/342716239136779"

test:
  facebook_app_id: 341926772543413
  facebook_secret: 14a850bdc51644e279dca141408208ba
  facebook_app_url: "http://apps.facebook.com/341926772543413"

staging:
  facebook_app_id: 250842391695084
  facebook_app_url: "http://apps.facebook.com/250842391695084"
  fqdn: "teste.votocomovamos.com.br"

production:
  facebook_app_id: 502204129793230
  facebook_app_url: "http://apps.facebook.com/502204129793230"
