common:
  facebook_app_id: 341926772543413
  facebook_secret: 14a850bdc51644e279dca141408208ba
  facebook_scopes: "offline_access,read_stream,email"
  facebook_app_url: "http://apps.facebook.com/341926772543413"

development:

test:

production:
  facebook_app_url: "http://apps.facebook.com/250842391695084/"

production:
  facebook_app_url: "http://apps.facebook.com/250842391695084/"
